#!/usr/bin/env bash
set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

dry_run="0"
[[ "${1:-}" == "--dry" ]] && dry_run="1"

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

target="$XDG_CONFIG_HOME/nvim"

if [[ -L "$target" && "$(readlink "$target")" == "$DOTFILES/nvim" ]]; then
    log "nvim already symlinked correctly"
else
    log "rm -rf $target"
    log "ln -s  $DOTFILES/nvim -> $target"
    if [[ $dry_run == "0" ]]; then
        rm -rf "$target"
        ln -s "$DOTFILES/nvim" "$target"
    fi
    log "nvim symlink created."
fi
